[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.30"

[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=15.1", "-C", "link-arg=-lSystem"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=15.1", "-C", "link-arg=-lSystem"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=15.1", "-C", "link-arg=-lSystem"]