[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.30"
MACOSX_DEPLOYMENT_TARGET = "14.0"
IPHONEOS_DEPLOYMENT_TARGET = "15.1"
CMAKE_OSX_DEPLOYMENT_TARGET = "15.1"

[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-lSystem"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-lSystem"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-lSystem"]